apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: yas
  app.kubernetes.io/environment: staging

images:
  - name: anhhnus/product-service
    newTag: v0.0.0
  - name: anhhnus/cart-service
    newTag: v0.0.0
  - name: anhhnus/order-service
    newTag: v0.0.0
  - name: anhhnus/customer-service
    newTag: v0.0.0
  - name: anhhnus/inventory-service
    newTag: v0.0.0
  - name: anhhnus/tax-service
    newTag: v0.0.0
  - name: anhhnus/media-service
    newTag: v0.0.0
  - name: anhhnus/search-service
    newTag: v0.0.0
  - name: anhhnus/storefront-bff
    newTag: v0.0.0
  - name: anhhnus/storefront
    newTag: v0.0.0
  - name: anhhnus/backoffice-bff
    newTag: v0.0.0
  - name: anhhnus/backoffice
    newTag: v0.0.0
  - name: anhhnus/sampledata-service
    newTag: v0.0.0
  - name: anhhnus/location-service
    newTag: v0.0.0
  - name: anhhnus/payment-service
    newTag: v0.0.0
  - name: anhhnus/payment-paypal-service
    newTag: v0.0.0
  - name: anhhnus/promotion-service
    newTag: v0.0.0
  - name: anhhnus/rating-service
    newTag: v0.0.0
  - name: anhhnus/recommendation-service
    newTag: v0.0.0
  - name: anhhnus/webhook-service
    newTag: v0.0.0
