# Title for the gitleaks configuration file.
title = "Gitleaks configuration for YAS Project"

[extend]
# Kế thừa các quy tắc mặc định của Gitleaks
useDefault = true

[allowlist]
description = "Gộp tất cả danh sách bỏ qua cho đồ án YAS"

# Gộp tất cả các đường dẫn cần bỏ qua vào đây
paths = [
    '''test-realm\.json''',
    '''realm-export''',
    '''keycloak-yas-realm-import\.yaml''',
    '''target/''',
    '''src/test/resources/''',
    '''automation-ui/''',
    '''\.gitleaksignore'''
]

# Gộp tất cả các Regex cần bỏ qua vào đây
regexes = [
    '''invalidPassword''',
    '''46c49daf-fa62-4744-883d-d32e810cfb9c''',
    '''590e533b-5a2d-4dd1-9419-d301f326cf0a'''
]