title = "Gitleaks configuration for YAS Project"

[extend]
useDefault = true

[allowlist]
description = "Whitelist triệt để cho đồ án YAS"

paths = [
    # Sử dụng regex rộng hơn để bắt toàn bộ các file liên quan đến cấu hình test
    '''test-realm\.json''',
    '''realm-export\.json''',
    '''keycloak-yas-realm-import\.yaml''',
    '''values\.yaml''',
    # Chặn đứng thư mục target và automation-ui
    '''target/.*''',
    '''automation-ui/.*''',
    '''src/test/resources/.*''',
    '''\.gitleaksignore'''
]

regexes = [
    # Bỏ qua mọi chuỗi có dạng secret giả lập thường gặp trong dự án
    '''invalidPassword''',
    '''[a-zA-Z0-9]{32}''', # Bỏ qua các chuỗi 32 ký tự (thường là secret key giả)
    '''46c49daf-fa62-4744-883d-d32e810cfb9c''',
    '''590e533b-5a2d-4dd1-9419-d301f326cf0a'''
]