apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  yas.server: |
    yas.local.com:53 {
        errors
        cache 30
        hosts {
            100.118.54.48 storefront.yas.local.com
            100.118.54.48 backoffice.yas.local.com
            100.118.54.48 identity.yas.local.com
            fallthrough
        }
        forward . /etc/resolv.conf
    }
