apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: prometheus-kube-prometheus-grafana-datasource
  namespace: observability
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://prometheus-kube-prometheus-prometheus.observability:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-kube-prometheus-alertmanager.observability:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
    - access: proxy
      isDefault: false
      name: Loki
      type: loki
      uid: loki
      url: http://loki-gateway.observability.svc.cluster.local:80
    - access: proxy
      isDefault: false
      name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.observability.svc.cluster.local:3200
      jsonData:
        nodeGraph:
          enabled: true
        serviceMap:
          datasourceUid: prometheus
        tracesToLogsV2:
          datasourceUid: loki
          filterByTraceID: true
          filterBySpanID: false
          tags:
            - key: service.name
              value: container
            - key: k8s.namespace.name
              value: namespace
