apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: yas
spec:
  selector:
    app: kafka-connect
  ports:
    - name: http
      port: 8083
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: yas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      enableServiceLinks: false


      containers:
        - name: kafka-connect
          image: debezium/connect:2.7.3.Final
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8083

          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: GROUP_ID
              value: yas-kafka-connect

            - name: CONFIG_STORAGE_TOPIC
              value: yas_connect_configs

            - name: OFFSET_STORAGE_TOPIC
              value: yas_connect_offsets

            - name: STATUS_STORAGE_TOPIC
              value: yas_connect_statuses

            - name: CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"

            - name: OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"

            - name: STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"

            - name: REST_ADVERTISED_HOST_NAME
              value: kafka-connect

          startupProbe:
            httpGet:
              path: /connectors
              port: http
            periodSeconds: 5
            failureThreshold: 60

          readinessProbe:
            httpGet:
              path: /connectors
              port: http
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /connectors
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20

          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 1Gi
