name: PR Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gitleaks-pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks scan
        run: |
          docker pull zricethezav/gitleaks:v8.18.4
          docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work zricethezav/gitleaks:v8.18.4 detect --source="." --config="/work/gitleaks.toml" --verbose --no-git
